### ISSUE TITLE
Support ticket header not localized in kitchen

### ISSUE THREAD

**Issue by joapalmer** [pancakeapp/pancake-payments-issues#4]
File:
/third_party/themes/pancake/views/modules/kitchen/new_ticket.php
AND
/third_party/themes/pancake/views/modules/kitchen/tickets.php

Line 2: "Support tickets" not a localized string. Cannot be translated.

**Comment by joapalmer** [comment]
In fact. These files has loads of unlocalized strings. Its odd as it would be really in the client access area/kitchen where localization is most critical...

**Comment by BrunoDeBarros** [comment]
Thanks for pointing these out to us - they'll be resolved in the next update to Pancake, which'll be out shortly.

**Comment by BrunoDeBarros** [comment]
If you have translations issues, though, it'd be a lot better to submit them to https://github.com/pancakeapp/translations/issues; that's where everything translation-related is.

**Comment by joapalmer** [comment]
Moving the issue to  https://github.com/pancakeapp/translations/issues for now.
